[package]
name = "vbox"
version = "0.1.0"
authors = ["Minkyu Jung <hestati@kaist.ac.kr>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"

[profile.release]
debug = false
opt-level = 1
lto = true
codegen-units = 1
